---

- name: Deploy tacho bmw
  hosts: all
  remote_user: pi
  tasks:
    - name: Copy custom config.txt
      become: true
      copy: 
        src: config.txt
        dest: /boot/config.txt
        
    - name: Unblock wifi
      command: rfkill unblock all
      become: yes

    - name: Copy wpa_supplicant
      template:
        src: wpa_supplicant.conf
        dest: /etc/wpa_supplicant/wpa_supplicant.conf
      when: wlanSSID is defined and wlanSSID != ""
      become: yes

    - name: Reboot
      become: true
      reboot:

    - name: set timezone
      timezone:
        name: "Europe/Berlin"
      become: yes


    - name: Copy resetCan
      become: true
      copy:
        src: resetCan
        dest: /bin/
        owner: root
        group: root
        mode: 0755
        
    - name: Copy binary
      become: true
      copy:
        src: ../go-tacho-bmw
        dest: /bin/go-tacho-bmw
        owner: root
        group: root
        mode: 0755

    - name: Copy service defintion
      become: true
      copy:
        src: tacho.service
        dest: /etc/systemd/system/
        
    - name: Restart and enable tacho service
      become: true
      systemd:
        name: tacho 
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Disable fake-hwclock
      become: true
      systemd:
        name: fake-hwclock
        enabled: no
        state: stopped
        daemon_reload: yes
    - name: Copy hwclock-set
      become: true
      copy:
        src: hwclock-set
        dest: /lib/udev/hwclock-set
        mode: 0755
        owner: root
        group: root